# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KINDER FOOD FINDER' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'SwiftKeychainWrapper', '~> 3.2'
pod 'GoogleSignIn'

  # Pods for KINDER FOOD FINDER

end
